DISEASE_INFO = {
    'Apple___Apple_scab': {
        'cause': 'Apple scab is primarily caused by the fungal pathogen Venturia inaequalis, which flourishes in cool, damp spring weather. The infection cycle begins when spores are discharged from fallen leaves during rainy periods, landing on emerging tissue. High humidity, frequent rainfall, and poor air circulation within the canopy create an ideal environment for the fungus to colonize young leaves and fruit.',
        'cure': 'To manage scab, apply protective fungicides early in the growing season, specifically between the green tip and petal fall stages. It is crucial to rake and destroy fallen leaves in autumn to eliminate the primary source of overwintering spores. Prune the tree canopy extensively to improve sunlight penetration and air movement, which helps foliage dry quickly after rain or dew.'
    },
    'Apple___Black_rot': {
        'cause': 'Black rot is caused by the fungus Botryosphaeria obtusa, which targets the fruit, foliage, and bark of apple trees. The pathogen typically enters the plant through existing wounds, such as those caused by insects, hail, or pruning cuts. It thrives in warm, humid conditions and survives the winter in mummified fruits and cankers on dead wood, providing a continuous source of inoculum.',
        'cure': 'Effective control begins with rigorous orchard sanitation; prune out all dead wood and cankers during the dormant season and remove mummified fruit from the tree. Apply recommended fungicides starting at the silver tip stage to protect developing tissues. Reducing plant stress through balanced fertilization and proper irrigation helps the tree naturally resist infection and limits the spread of the fungal spores.'
    },
    'Apple___Cedar_apple_rust': {
        'cause': 'This disease is caused by Gymnosporangium juniperi-virginianae, a unique fungal pathogen that requires two different hosts—apple trees and Eastern Red Cedars—to complete its complex life cycle. In wet spring weather, spores from gelatinous galls on cedar trees are carried by the wind to apple leaves. The presence of nearby junipers or cedars significantly increases the likelihood of severe infection during rainy seasons.',
        'cure': 'Breaking the infection cycle is most effective when you remove nearby cedar trees within a several-hundred-yard radius of the orchard. If removal is not feasible, apply preventative fungicides to apple trees from the pink bud stage through the end of the rainy period. Additionally, planting rust-resistant apple cultivars is a highly recommended long-term strategy for homeowners and commercial growers alike.'
    },
    'Apple___healthy': {
        'cause': 'A healthy apple tree indicates that the plant is growing under optimal environmental conditions with no detectable presence of pathogenic fungi or bacteria. This state is achieved when the tree receives sufficient sunlight (at least six to eight hours daily), balanced soil nutrients, and appropriate moisture levels. Healthy trees exhibit vigorous growth, vibrant green foliage, and consistent fruit production throughout the season.',
        'cure': 'To maintain this healthy status, continue a consistent regimen of watering, mulching, and annual dormant pruning. Regularly monitor the orchard for the first signs of pests or nutritional deficiencies to intervene early. Maintaining excellent hygiene, such as removing fallen debris and keeping tools sanitized, prevents the introduction of pathogens and ensures the long-term productivity and vitality of the apple trees.'
    },
    'Blueberry___healthy': {
        'cause': 'Blueberry plants are considered healthy when they show no symptoms of disease or nutrient stress, thriving in their specific requirement for acidic soil. Optimal growth occurs when the soil pH is maintained between 4.5 and 5.5, and the plants receive consistent moisture. A robust root system and absence of leaf spotting suggest that environmental stressors and fungal pathogens are well-managed.',
        'cure': 'Sustainability of blueberry health depends on maintaining soil acidity through the application of elemental sulfur or acidic fertilizers. Ensure the plants receive about one inch of water per week, especially during fruit development, and use organic mulch to retain moisture and suppress weeds. Periodic pruning to remove old canes will encourage new, productive growth and maintain excellent airflow throughout the bush.',
    },
    'Cherry_(including_sour)___Powdery_mildew': {
        'cause': 'Powdery mildew in cherries is caused by Podosphaera clandestina, a fungus that appears as white, flour-like patches on leaves and fruit. Unlike many other fungi, it does not require liquid water to infect; instead, it thrives in high humidity and moderate temperatures. The spores are easily dispersed by wind, often infecting young, succulent growth in overcrowded or poorly ventilated orchards.',
        'cure': 'Control this disease by applying sulfur-based fungicides or horticultural oils at the first sign of white patches. Increasing the spacing between trees and performing strategic pruning will enhance air circulation, which naturally lowers the humidity levels within the canopy. Avoid excessive nitrogen fertilization in the late spring, as this stimulates the tender new growth that is most susceptible to infection.',
    },
    'Cherry_(including_sour)___healthy': {
        'cause': 'A healthy cherry tree displays glossy, deep green leaves and shows no signs of fungal spotting, bacterial cankers, or powdery coatings. This health is a result of favorable site selection with well-drained soil and adequate sun exposure. When the tree’s nutritional needs are met and environmental stressors are low, the plant can devote its energy to fruit production and winter hardiness.',
        'cure': 'Maintain cherry health by following a disciplined pruning schedule to keep the center of the tree open to light and air. Apply a balanced fertilizer in early spring and ensure the tree is deeply watered during dry spells. Regularly scout for aphids or borers, as preventing insect damage reduces the entry points for opportunistic diseases, keeping the tree productive for years.',
    },
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': {
        'cause': 'Gray leaf spot is caused by the fungus Cercospora zeae-maydis, which thrives during periods of extended leaf wetness and high relative humidity. The pathogen survives the winter in corn residue on the soil surface. When temperatures rise and humidity exceeds 90%, spores are produced and splashed or blown onto lower leaves, creating rectangular lesions that eventually hinder the plant’s photosynthesis.',
        'cure': 'To manage this disease, select corn hybrids with high resistance ratings and practice a two-year crop rotation to allow surface residue to decompose. In cases of high disease pressure, apply foliar fungicides during the silking stage to protect the upper leaves. Tillage can also be used to bury infected stalks, though this must be balanced with soil conservation and erosion goals.',
    },
    'Corn_(maize)___Common_rust_': {
        'cause': 'Common rust is caused by the fungus Puccinia sorghi, which produces distinctive cinnamon-brown pustules on both the upper and lower leaf surfaces. The spores do not typically overwinter in cold climates; instead, they are carried northward by wind currents from warmer southern regions each year. High humidity and moderate temperatures around 60 to 70 degrees Fahrenheit promote rapid infection and spread.',
        'cure': 'The most effective way to prevent common rust is to plant resistant corn hybrids, which are widely available to growers. If the infection occurs early in the season and environmental conditions favor spread, a timely application of systemic fungicides can protect the yield. Proper field management, including balanced nitrogen levels and effective weed control, helps the crop remain vigorous and less susceptible.',
    },
    'Corn_(maize)___Northern_Leaf_Blight': {
        'cause': 'Northern leaf blight is caused by Exserohilum turcicum, a fungal pathogen that manifests as long, cigar-shaped grayish-green lesions on corn leaves. The disease is most prevalent in environments characterized by moderate temperatures and frequent dew or rainfall. The fungus overwinters in infected corn debris, and spores are splashed onto new plants during the spring, leading to significant reductions in grain yield.',
        'cure': 'Management strategies include the use of resistant hybrids and practicing crop rotation with non-host plants like soybeans or small grains. Applying fungicides at the first sign of lesions can be economically viable if the disease appears before or during the tasseling stage. Additionally, managing corn residue through tillage can help reduce the amount of inoculum present for the following season’s crop.',
    },
    'Corn_(maize)___healthy': {
        'cause': 'Healthy corn indicates that the crop has been provided with an ideal balance of nitrogen, phosphorus, and potassium, along with consistent moisture throughout its growth stages. The absence of lesions or discoloration suggests that the field management has effectively suppressed fungal pathogens and insect pests. Healthy corn stalks are sturdy and the leaves are a deep, uniform green, maximizing photosynthesis.',
        'cure': 'Maintain corn health by implementing a robust soil testing program to ensure accurate fertilization and pH levels. Use integrated pest management (IPM) to monitor for early signs of insects or disease. Ensuring proper planting density prevents overcrowding, which reduces humidity within the crop canopy. Consistent irrigation during the critical silking and grain-filling stages is essential to maintaining this healthy, productive state.',
    },
    'Grape___Black_rot': {
        'cause': 'Grape black rot is caused by the fungus Guignardia bidwellii and is considered one of the most destructive diseases in humid vineyard regions. The fungus overwinters in mummified berries left on the vine or ground. In spring, rainfall triggers the release of spores that infect young leaves and developing fruit clusters, eventually turning berries into hard, black, shriveled "mummies."',
        'cure': 'Control black rot by removing all mummified fruit from the vineyard during the dormant season to eliminate the source of infection. Apply preventative fungicides starting when new shoots are several inches long and continuing through the bloom period. Maintain a rigorous pruning schedule to ensure the canopy is open, allowing for rapid drying of foliage and better coverage of fungicide sprays.',
    },
    'Grape___Esca_(Black_Measles)': {
        'cause': 'Esca is a complex "wood disease" caused by several types of fungi that infect the trunk and branches of grapevines, often entering through large pruning wounds. These pathogens decay the internal wood and produce toxins that cause characteristic "tiger-stripe" patterns on leaves and dark spots on fruit. It is a chronic condition that can lead to sudden vine collapse in hot weather.',
        'cure': 'There is no simple chemical cure for Esca, so management focuses on prevention and sanitation. When pruning, use wound sealants to prevent fungal entry and sanitize tools between vines. If a vine shows symptoms, prune back to healthy wood or remove and replace the entire plant. Reducing vine stress through proper irrigation and nutrition can help prolong the life of infected plants.',
    },
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': {
        'cause': 'Leaf blight, caused by the fungus Pseudocercospora vitis, typically appears late in the growing season and is most severe in warm, moist climates. The fungus causes irregular reddish-brown spots on the leaves, which can lead to premature leaf drop if left unchecked. While it rarely kills the vine, the loss of foliage reduces the plant\'s ability to produce sugar for the fruit.',
        'cure': 'Manage leaf blight by applying appropriate fungicides during the mid-to-late summer months if environmental conditions remain humid. Vineyard sanitation is vital; raking and composting fallen leaves can reduce the amount of fungus that overwinters in the soil. Improving the trellis system to increase airflow around the foliage will also help decrease the duration of leaf wetness and limit fungal growth.',
    },
    'Grape___healthy': {
        'cause': 'A healthy grapevine shows vigorous shoot growth, uniform green leaves, and well-developed fruit clusters without any signs of spotting or rot. This status is the result of proper site selection, including full sun and well-drained soil, alongside careful management of pests and pathogens. When vines are healthy, they can efficiently store carbohydrates in their wood to survive the winter months.',
        'cure': 'To keep grapes healthy, perform annual dormant pruning to balance fruit production with vegetative growth. Monitor for common pests like leafhoppers and maintain a consistent watering schedule that targets the roots rather than the foliage. Regular soil testing and applying organic compost or balanced fertilizers will ensure the vines have the necessary nutrients to resist disease and produce high-quality harvests.',
    },
    'Orange___Haunglongbing_(Citrus_greening)': {
        'cause': 'Citrus Greening, or HLB, is a devastating disease caused by the bacterium Candidatus Liberibacter asiaticus, which is transmitted by the Asian citrus psyllid insect. Once infected, the bacteria move into the tree’s vascular system, blocking the flow of nutrients. This leads to yellowing leaves, stunted growth, and bitter, misshapen fruit that remains green even when ripe, eventually killing the tree.',
        'cure': 'Currently, there is no known cure for a tree once it is infected with HLB. Management focuses strictly on controlling the psyllid population through insecticides and biological controls. Infected trees should be removed immediately to prevent them from serving as a reservoir for the bacteria. Growers should only use certified disease-free nursery stock and monitor their groves frequently for early symptoms.',
    },
    'Peach___Bacterial_spot': {
        'cause': 'Bacterial spot is caused by Xanthomonas arboricola pv. pruni and is most prevalent in regions with high rainfall and sandy soils. The bacteria overwinter in twig cankers and are spread to leaves and fruit by wind-blown rain. The disease causes small, water-soaked spots that eventually fall out, leaving "shot-holes" in the leaves, and can cause deep pitting or cracking in the fruit.',
        'cure': 'To control bacterial spot, apply copper-based bactericides or antibiotics during the early spring and throughout the growing season if conditions are wet. Planting resistant peach cultivars is the most effective long-term solution for areas prone to the disease. Avoid using overhead irrigation, as splashing water spreads the bacteria, and maintain balanced tree nutrition to help the plant recover from foliage loss.',
    },
    'Peach___healthy': {
        'cause': 'Healthy peach trees are characterized by lush, green foliage, smooth bark, and a lack of spotting on the fruit. This state indicates that the tree is growing in a location with excellent drainage and is receiving adequate chilling hours during the winter. When the tree is free from bacterial and fungal pathogens, it can produce a heavy crop of high-quality, sweet fruit.',
        'cure': 'Maintain peach health by thinning the fruit in early summer to prevent branch breakage and ensure larger, healthier peaches. Prune the trees into an "open center" shape to allow maximum light and air into the canopy. Apply a dormant oil spray in late winter to control overwintering pests, and keep the area around the trunk free of weeds and fallen debris.',
    },
    'Pepper,_bell___Bacterial_spot': {
        'cause': 'Bacterial spot in bell peppers is caused by Xanthomonas species and thrives in warm, rainy environments. The bacteria are often introduced through contaminated seeds or infected transplants. Once in the garden, the pathogen spreads rapidly via water splash, wind, or handling wet plants. It causes dark, circular spots on leaves, leading to defoliation and sunscald on the developing pepper fruits.',
        'cure': 'Management begins with using certified disease-free seeds and resistant varieties. If symptoms appear, apply copper-based sprays every 7 to 10 days to slow the spread, though this is less effective in very rainy weather. Practice a three-year crop rotation with non-solanaceous plants and avoid overhead watering. Always sanitize garden tools and avoid working in the pepper patch when the foliage is wet.',
    },
    'Pepper,_bell___healthy': {
        'cause': 'Healthy bell pepper plants exhibit sturdy stems, dark green leaves, and consistent flowering and fruit set. This condition is maintained by providing the plants with full sun, consistent moisture, and soil rich in organic matter. When the environment is kept free of bacterial pathogens and insect vectors like aphids, the peppers can grow to their full size and reach deep coloration.',
        'cure': 'To keep peppers healthy, use mulch to maintain even soil moisture and prevent soil-borne pathogens from splashing onto the leaves. Provide a balanced fertilizer low in nitrogen but high in phosphorus and potassium to encourage fruit production over excessive foliage. Stake the plants to keep the fruit off the ground and monitor regularly for early signs of pests like pepper weevils.',
    },
    'Potato___Early_blight': {
        'cause': 'Early blight is caused by the fungus Alternaria solani and typically affects older potato foliage first. The disease is characterized by dark, concentric rings on the leaves that resemble a target. It thrives in moderate to warm temperatures and is exacerbated by periods of heavy dew or frequent rainfall. While it rarely kills the plant, it significantly reduces the size and quality of the tubers.',
        'cure': 'Manage early blight by applying protective fungicides when the first symptoms appear on the lower leaves. Practice a three-year crop rotation with crops other than tomatoes or eggplants to reduce the fungal population in the soil. Ensure the plants have adequate nitrogen and irrigation throughout the season, as stressed or nutrient-deficient potatoes are much more susceptible to severe infection by this fungus.',
    },
    'Potato___Late_blight': {
        'cause': 'Late blight is a highly destructive disease caused by the oomycete Phytophthora infestans, the pathogen responsible for the Irish Potato Famine. It thrives in cool, wet weather and spreads with incredible speed via windborne spores. It causes large, dark, water-soaked lesions on leaves and stems, and can rot entire potato tubers in the ground or in storage within just a few days.',
        'cure': 'Prevention is key for late blight; plant only certified, disease-free seed potatoes and choose resistant varieties if available. If the disease is detected in the area, apply preventative fungicides regularly. If a plant becomes infected, it must be removed and destroyed immediately to protect nearby crops. Avoid overhead irrigation and ensure the potato hills are well-covered with soil to protect the tubers.',
    },
    'Potato___healthy': {
        'cause': 'Healthy potatoes show vigorous green top growth and are free from wilting, spotting, or yellowing. This indicates the plants are growing in well-drained, loose soil with adequate moisture and nutrients. When soil-borne pathogens are absent and the environment is managed to prevent moisture stress, the plant can direct its energy toward developing large, starchy tubers that store well after harvest.',
        'cure': 'Maintain potato health by hilling soil around the base of the plants to protect tubers from sunlight and pests. Practice consistent watering, aiming for about an inch of water per week, and use organic mulches to regulate soil temperature. Rotating crops every year and removing all tubers from the ground at harvest will prevent the carryover of diseases and pests to the next season.',
    },
    'Raspberry___healthy': {
        'cause': 'Healthy raspberries are characterized by strong, upright canes, vibrant green foliage, and abundant fruit clusters. This state is achieved when the plants are grown in well-drained soil with plenty of organic matter and a slightly acidic pH. Proper spacing and a lack of fungal infections like anthracnose allow the canes to produce high-quality berries throughout their specific bearing season.',
        'cure': 'To keep raspberries healthy, prune out fruited canes immediately after harvest to improve airflow and provide room for new growth. Maintain a thick layer of mulch to keep the roots cool and moist while suppressing weeds. Regularly check for signs of cane borers or viruses, and ensure the plants receive adequate water during the flowering and fruiting stages to maximize berry size.',
    },
    'Soybean___healthy': {
        'cause': 'A healthy soybean crop is indicated by a uniform stand of plants with deep green leaves and successful pod development. This suggests that the soil has adequate levels of phosphorus and potassium, and that nitrogen-fixing bacteria are active in the root nodules. When the field is free of significant pest pressure and fungal blights, the soybeans can reach their full yield potential.',
        'cure': 'Maintain soybean health through regular field scouting for pests like soybean aphids or Japanese beetles. Use high-quality, treated seeds to protect against early-season soil pathogens and ensure proper planting depth. Practicing crop rotation with corn or small grains helps break the cycles of host-specific pests and diseases, while maintaining balanced soil fertility ensures the plants have the resilience to withstand environmental stress.',
    },
    'Squash___Powdery_mildew': {
        'cause': 'Powdery mildew in squash is caused by fungi such as Podosphaera xanthii, which appear as white, dusty spots on leaves and stems. The disease thrives in warm temperatures and high humidity, though it does not need rain to spread. In fact, heavy rain can sometimes wash the spores away. Overcrowded plantings and shade contribute to the rapid development and spread of this fungus.',
        'cure': 'To treat powdery mildew, apply fungicides containing sulfur, neem oil, or potassium bicarbonate at the first sign of infection. Improving the spacing between squash plants will increase air circulation and sunlight, which naturally inhibits fungal growth. Whenever possible, select squash varieties that are bred for resistance to powdery mildew, and avoid handling the plants when they are wet or highly humid.',
    },
    'Strawberry___Leaf_scorch': {
        'cause': 'Leaf scorch is caused by the fungus Diplocarpon earlianum and is common in strawberries during warm, moist weather. The disease produces small purplish spots on the upper leaf surface that eventually enlarge and coalesce, making the leaf look "scorched" or burnt. Severe infections can weaken the plant, reduce fruit size, and make the strawberry bed less productive over several growing seasons.',
        'cure': 'Manage leaf scorch by removing and destroying old foliage after the harvest is complete. Apply appropriate fungicides during the early spring as new leaves emerge to protect them from spores overwintering in the mulch. Ensure that the strawberry bed is not overcrowded by thinning plants regularly, and use drip irrigation to keep the leaves dry, which discourages the germination of fungal spores.',
    },
    'Strawberry___healthy': {
        'cause': 'Healthy strawberry plants have bright green, turgid leaves and produce an abundance of blossoms and fruit without signs of rotting or spotting. This health is a result of planting in full sun and well-drained soil, often in raised beds. When the plants are properly spaced and mulched with straw, they remain free from soil-borne pathogens and many common foliage diseases.',
        'cure': 'Maintain strawberry health by "renovating" June-bearing beds after harvest, which involves mowing the foliage and thinning the plants. Provide consistent moisture, especially during fruit development, and use a straw mulch to keep berries off the soil. Regularly inspect for pests like slugs or tarnished plant bugs, and replace the entire bed every three to four years to maintain vigor and productivity.',
    },
    'Tomato___Bacterial_spot': {
        'cause': 'Bacterial spot is caused by Xanthomonas species and is one of the most common tomato diseases in warm, wet climates. The bacteria are often carried on seeds or transplants and spread through the garden via wind-driven rain or contaminated tools. It causes small, dark, greasy-looking spots on leaves and scabby lesions on the fruit, which can lead to significant crop loss.',
        'cure': 'There is no complete cure for bacterial spot once it takes hold, but copper-based sprays can help limit the spread. Use only certified disease-free seeds and transplants, and practice a long crop rotation. Avoid overhead watering and handle plants only when they are dry. Mulching around the base of the plant can also prevent bacteria in the soil from splashing onto the foliage.',
    },
    'Tomato___Early_blight': {
        'cause': 'Early blight is caused by the fungus Alternaria solani and typically appears on the lower, older leaves of tomato plants. It is identified by brown spots with concentric "target" rings. The fungus thrives in humid conditions and can survive in the soil or on infected plant debris for several years. If left unmanaged, it can cause total defoliation, leading to sunscalded fruit.',
        'cure': 'Control early blight by removing the lower leaves of the plant to prevent contact with the soil and improve airflow. Apply fungicides like chlorothalonil or copper-based products at the first sign of spotting. Practice a three-year crop rotation and ensure plants are spaced at least two feet apart. Mulching is highly effective at preventing the fungal spores from splashing up onto the leaves.',
    },
    'Tomato___Late_blight': {
        'cause': 'Late blight is caused by the oomycete Phytophthora infestans and is a devastating disease that can destroy an entire tomato crop within days. It favors cool, wet, and cloudy weather, spreading through windborne spores. It causes large, dark, olive-green to black water-soaked patches on leaves and stems, and a firm, chocolate-brown rot on the fruit that makes it inedible.',
        'cure': 'Because late blight spreads so rapidly, prevention is essential. Plant resistant varieties and avoid overhead watering. If you identify late blight, remove the entire plant, bag it, and dispose of it immediately—do not compost it. In areas where late blight is a known seasonal issue, regular applications of preventative fungicides are necessary to protect the crop during periods of high humidity.',
    },
    'Tomato___Leaf_Mold': {
        'cause': 'Leaf mold is caused by the fungus Passalora fulva and is most common in greenhouse-grown tomatoes where humidity is high and air circulation is limited. The disease appears as pale green or yellow spots on the upper leaf surface, with a velvety, olive-green fungal growth on the underside. It can cause leaves to wither and drop, significantly reducing the plant’s productivity.',
        'cure': 'Manage leaf mold by significantly improving ventilation and reducing the relative humidity around the plants to below 85%. In greenhouses, use fans and heat to keep the air moving and the foliage dry. Prune the plants to remove excess leaves and increase spacing. Fungicides can be effective, but selecting tomato varieties with genetic resistance to leaf mold is the most efficient solution.',
    },
    'Tomato___Septoria_leaf_spot': {
        'cause': 'Septoria leaf spot is caused by the fungus Septoria lycopersici and is characterized by numerous small, circular spots with dark borders and gray centers. Like early blight, it starts on the bottom leaves and moves upward. It thrives in warm, wet weather and is primarily spread by splashing water. While it doesn\'t affect the fruit directly, the loss of leaves weakens the plant.',
        'cure': 'To control Septoria, remove and destroy infected leaves as soon as they appear. Use drip irrigation instead of sprinklers to keep the foliage dry, and apply a thick layer of mulch to create a barrier between the soil and the plant. Copper-based fungicides or other labeled products can be applied every 7 to 10 days during rainy periods to protect new growth.',
    },
    'Tomato___Spider_mites Two-spotted_spider_mite': {
        'cause': 'Spider mites are tiny arachnids that thrive in hot, dry conditions. They feed by piercing plant cells and sucking out the contents, leading to a "stippled" or yellow-dotted appearance on the leaves. In severe infestations, fine silk webbing can be seen covering the foliage. Because they reproduce so quickly in the heat, they can rapidly overwhelm a tomato plant if ignored.',
        'cure': 'Control spider mites by spraying the plants with a strong stream of water to knock them off the leaves and increase humidity, which they dislike. Use insecticidal soaps, neem oil, or horticultural oils to treat the undersides of the leaves where they congregate. Avoid using broad-spectrum insecticides that kill the natural predators of mites, such as ladybugs and predatory mites.',
    },
    'Tomato___Target_Spot': {
        'cause': 'Target spot is caused by the fungus Corynespora cassiicola and is most common in tropical and subtropical regions with high humidity. It causes lesions on leaves that have distinct concentric rings, similar to early blight, but it also causes sunken, brown spots on the fruit. The fungus survives on crop debris and alternate hosts, and is spread by wind and splashing rain.',
        'cure': 'Manage target spot by maintaining a clean garden environment and removing all plant debris after harvest. Apply fungicides such as mancozeb or copper-based products when weather conditions are humid and warm. Increase plant spacing to improve airflow through the canopy and use stakes or cages to keep the foliage and fruit off the ground, which reduces the risk of infection.',
    },
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': {
        'cause': 'This viral disease is transmitted by the silverleaf whitefly and is particularly common in warm climates. The virus causes severe stunting, upright growth, and leaves that are small, yellow, and curled upward. If a plant is infected early in its growth, it will often fail to produce any fruit, and the virus can spread quickly through a garden via the whitefly population.',
        'cure': 'There is no cure for a virus-infected plant; it should be removed and destroyed immediately to prevent further spread. Management focuses on whitefly control using reflective mulches, yellow sticky traps, and insecticidal soaps. Whenever possible, plant tomato varieties that are specifically labeled as resistant to TYLCV (Tomato Yellow Leaf Curl Virus) to ensure a successful harvest in high-risk areas.',
    },
    'Tomato___Tomato_mosaic_virus': {
        'cause': 'Tomato mosaic virus (ToMV) is a highly stable virus that can be spread by mechanical means, such as handling plants, using contaminated tools, or even through tobacco products. It causes a mottled, mosaic-like pattern of light and dark green on the leaves, along with leaf distortion. The virus can persist for years in the soil or on dried plant remains and seeds.',
        'cure': 'Prevent the spread of ToMV by practicing excellent hygiene: wash hands with soap and water after handling plants and sanitize tools frequently with a bleach solution. Remove and destroy any infected plants immediately. Avoid smoking or using tobacco near tomato plants, as the virus can be present in tobacco. Plant certified disease-free seeds and select resistant tomato varieties to minimize the risk.',
    },
    'Tomato___healthy': {
        'cause': 'A healthy tomato plant is a result of providing deep, fertile soil, consistent watering at the root zone, and at least eight hours of direct sunlight. The absence of spots, wilting, or pests indicates that the grower has successfully managed the environment and practiced good sanitation. Healthy tomato plants have thick stems and dark green foliage, supporting a heavy crop of ripening fruit.',
        'cure': 'Maintain tomato health by using organic mulch to keep the soil moisture consistent and prevent blossom end rot. Support the plants with sturdy cages or stakes to keep fruit off the ground and improve air movement. Regularly prune the "suckers" or lower leaves to enhance sunlight penetration and perform weekly inspections to catch any potential pest or disease issues before they become severe.',
    }
}